sudo: required
language: generic

services:
 - docker

before_install:
 - make install_dependencies

script:
 - make test

after_success:
 - make build_prod
 - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
 - make push_images

cache:
  directories:
   - server/vendor
